InnoDB backup with xtrabackup now handles error: return value of xtrabackup is checked, size and md5sum are checked after backup was successful If a table contains special characters a global read lock is aquired while copying it so all copied files are not corrupted on transfer now.

diff --git a/bin/backup-mysql b/bin/backup-mysql
--- a/bin/backup-mysql
+++ b/bin/backup-mysql
@@ -22,7 +22,7 @@ remote_backup_dir="$($ssh mktemp --directory --tmpdir=\"${REMOTE_DIR}\")"
 
 info "Generating mysql config"
 mysql_cnf="${BACKUP_DIR}/my.cnf"
-#"$(dirname "$(readlink --canonicalize "$0")")"/backup-mysql-config.sh > "$mysql_cnf"
+"$(dirname "$(readlink --canonicalize "$0")")"/backup-mysql-config.sh > "$mysql_cnf"
 
 cat >>"$mysql_cnf" <<-ENDL
 	
@@ -57,11 +57,33 @@ fi
 info "Starting InnoDB backup"
 md5sum_file="${LOG_DIR}/$(basename "$BACKUP_INNODB").md5sum"
 size_file="${LOG_DIR}/$(basename "$BACKUP_INNODB").size"
+remote_error_file="$($ssh mktemp)"
 
-$ssh "$xtrabackup_bin --defaults-file=\"$remote_mysql_cnf\" \"$remote_backup_dir\" | $COMPRESS_BIN $COMPRESS_PARAMS" 2>"${LOG_DIR}/xtrabackup.log" |
-tee >(md5sum > "$md5sum_file") >(wc --bytes > "$size_file") > "$BACKUP_INNODB"
+$ssh "( $xtrabackup_bin --defaults-file=\"$remote_mysql_cnf\" \"$remote_backup_dir\" || echo \"\$?\" > \"$remote_error_file\") | $COMPRESS_BIN $COMPRESS_PARAMS" 2>"${LOG_DIR}/xtrabackup.log" |
+tee >(md5sum | dd bs=32 count=1 > "$md5sum_file" 2>/dev/null) >(wc --bytes > "$size_file") > "$BACKUP_INNODB"
+
+$ssh "test -s \"$remote_error_file\"" &&
+error "Failed to create innodb backup, see log for more details" &&
+exit $ERR_INNOBACKUP
 
 $ssh "cat \"${remote_backup_dir}\"/xtrabackup_checkpoints" > "${MYSQL_DIR}/xtrabackup_checkpoints"
+
+size_is="$(stat --format="%s" "$BACKUP_INNODB")"
+size_should="$(< "$size_file")"
+if (( size_is == size_should )); then
+	info "  size OK"
+else
+	error "  size mismatch: is $size_is, should be $size_should"
+	exit $ERR_INNOBACKUP
+fi
+
+info "  checking md5sum"
+if [ "$(md5sum "$BACKUP_INNODB" | dd bs=32 count=1 2>/dev/null)" == "$(< $md5sum_file)" ]; then
+	info "  md5sum OK"
+else
+	error "  md5sum mismatch, backup file seems to be corrupt"
+	exit $ERR_INNOBACKUP
+fi
 
 # FIXME: check that everything is ok
 
@@ -82,6 +104,7 @@ function backup-mysql-fix-name() {
 	name="$(echo "$name" | sed 's/@\(00\)\([0-9a-f]\{2\}\)/\\x\1\\x\2/g')"
 	
 	# FIXME: translate all the other crap from http://dev.mysql.com/doc/refman/5.1/en/identifier-mapping.html
+	# See also: http://www.skysql.com/blogs/kolbe/demystifying-identifier-mapping
 	[ "${name/@/}" != "$name" ] && warn "database/table name \"$name\" stil contains untranslatable characters"
 	
 	echo -e "$name"
@@ -149,29 +172,39 @@ while read -u $file_reader; do
 	
 	info "Working on table $counter of $tables_count: \"$database.$table\""
 	
-	# Disable mysql locking, etc if table name still contains encoded special characters
+	# Require global locking for table if table name still contains encoded special characters
 	if [ "${database/@/}" != "${database}" ] || [ "${table/@/}" != "${table}" ]; then
-		ignore_mysql="yes"
+		global_lock="yes"
+		warn "  table \"$database.$table\" requires global lock"
 	else
-		ignore_mysql=
+		global_lock=
 	fi
 	
-	if [ -z "$ignore_mysql" ]; then
+	# Try table lock
+	if [ -z "$global_lock" ]; then
 		if ! lock_msg=$(backup-mysql-query "LOCK TABLE \`$database\`.\`$table\` READ;" $mysql_control $mysql_result); then
 			# Fallback
-			warn "failed to lock table \"$database.$table\", falling back to FLUSH TABLES WITH READ LOCK (error: \"$lock_msg\")"
-			! flush_msg=$(backup-mysql-query "FLUSH TABLES WITH READ LOCK;" $mysql_control $mysql_result) &&
-			error "failed to flush tables with read lock (error: \"$flush_msg\")" && exit $ERR_MYSQL
+			warn "failed to lock table \"$database.$table\", using global lock ($lock_msg)"
+			global_lock="yes"
 			
 		else
 			! flush_msg=$(backup-mysql-query  "FLUSH TABLE \`$database\`.\`$table\`;" $mysql_control $mysql_result) &&
-			error "failed to flush table \"$database.$table\" (error: \"$flush_msg\")" && exit $ERR_MYSQL
+			error "failed to flush table \"$database.$table\" ($flush_msg)" && exit $ERR_MYSQL
 		fi
 	fi
-		
+	
+	# Retry with global lock
+	if [ -n "$global_lock" ]; then
+		! flush_msg=$(backup-mysql-query "FLUSH TABLES WITH READ LOCK;" $mysql_control $mysql_result) &&
+		error "failed to flush tables with read lock ($flush_msg)" && exit $ERR_MYSQL
+	fi
+	
 	for file_remote in $($ssh "ls \"${REMOTE_DIR}/image/var/lib/mysql/${database_dir}/${table_file}\".*"); do
 		# Skip innodb data files
-		[ "${file_remote%.ibd}" != "${file_remote}" ] && continue
+		if [ "${file_remote%.ibd}" != "${file_remote}" ]; then
+			info "  skipping InnoDB data file \"$(basename "$(dirname "$file_remote")")/$(basename "$file_remote")\""
+			continue
+		fi
 		
 		info "  transfering \"$(basename "$(dirname "$file_remote")")/$(basename "$file_remote")\""
 		
@@ -184,10 +217,8 @@ while read -u $file_reader; do
 		touch --date="$date_remote" "$file_local"
 	done
 	
-	if [ -z "$ignore_mysql" ]; then
-		! unlock_msg=$(backup-mysql-query "UNLOCK TABLES;" $mysql_control $mysql_result) &&
-		error "failed to unlock table \"$database.$table\" (error: \"$unlock_msg\")" && exit $ERR_MYSQL
-	fi
+	! unlock_msg=$(backup-mysql-query "UNLOCK TABLES;" $mysql_control $mysql_result) &&
+	error "failed to unlock table \"$database.$table\" ($unlock_msg)" && exit $ERR_MYSQL
 done
 
 ################################################################################
