Added backup-host:  * wraps backup-files and backup-mysql to create a full backup of a host  * handles incremental backups, calculates if backup should be incremental and from which it should increment
Other changes:
 * moved helper functions to backup-read-config.sh
 * renamed variable LOG_DIR to STATUS_DIR
 * now two separate exclude_lists for rsync and tar exists

diff --git a/bin/backup-files b/bin/backup-files
--- a/bin/backup-files
+++ b/bin/backup-files
@@ -2,34 +2,11 @@
 
 . "$(dirname "$(readlink --canonicalize "$0")")"/backup-read-config.sh
 
-# Incremental
-REFERENCE="$1"
-
 # Where is the host located
 backup-find-backend
 
-
-################################################################################
-#
-# FOLDERS
-#
-################################################################################
-
-if ! err=$(mkdir --parent "$MIRROR_DIR" 2>&1); then
-	error "failed to create basedir \"$BASEDIR\": error \"$err\"!"
-	exit $ERR_STORAGE
-fi
-
-if ! err=$(mkdir --parent "$LOG_DIR" 2>&1); then
-	error "failed to create logdir \"$LOG_DIR\": error \"$err\"!"
-	exit $ERR_STORAGE
-fi
-
-if ! err=$(mkdir --parent "$BACKUP_DIR" 2>&1); then
-	error "failed to create backupdir \"$BACKUP_DIR\": error \"$err\"!"
-	exit $ERR_STORAGE
-fi
-
+# Prepare all folders
+backup-create-folders
 
 ################################################################################
 #
@@ -50,6 +27,8 @@ if [ "${FAKEROOT,,*}" == "yes" ]; then
 	fi
 	
 	fakeroot_cmd=( "$fakeroot_bin" -i "${FAKEROOT_STATUS}" -s "$FAKEROOT_STATUS" -- )
+else
+	fakeroot_cmd=( "env" )
 fi
 
 # Check rsync
@@ -61,25 +40,21 @@ fi
 rsync_cmd=( "$RSYNC_BIN" ${RSYNC_PARAMS} )
 
 # Check exclude list
-if [ -n "${EXCLUDE_DEFAULT}" ]; then
-	if [ -r "${EXCLUDE_DEFAULT}" ]; then
-		info "using exclude file \"${EXCLUDE_DEFAULT}\"."
-		rsync_cmd=( "${rsync_cmd[@]}" "--exclude-from=${EXCLUDE_DEFAULT}" )
-	else
-		info "exclude file \"${EXCLUDE_DEFAULT}\" not found/readable!"
-	fi
+if [ -r "${RSYNC_EXCLUDE_DEFAULT}" ]; then
+	info "using exclude file \"${RSYNC_EXCLUDE_DEFAULT}\"."
+	rsync_cmd=( "${rsync_cmd[@]}" "--exclude-from=${RSYNC_EXCLUDE_DEFAULT}" )
+else
+	info "exclude file \"${RSYNC_EXCLUDE_DEFAULT}\" not found/readable!"
 fi
 
-if [ -n "${EXCLUDE_FROM}" ]; then
-	if [ -r "${EXCLUDE_FROM}" ]; then
-		info "using exclude file \"${EXCLUDE_FROM}\"."
-		rsync_cmd=( "${rsync_cmd[@]}" "--exclude-from=${EXCLUDE_FROM}" )
-	else
-		info "exclude file \"${EXCLUDE_FROM}\" not found/readable!"
-	fi
+if [ -r "${RSYNC_EXCLUDE_HOST}" ]; then
+	info "using exclude file \"${RSYNC_EXCLUDE_HOST}\"."
+	rsync_cmd=( "${rsync_cmd[@]}" "--exclude-from=${RSYNC_EXCLUDE_HOST}" )
+else
+	info "exclude file \"${RSYNC_EXCLUDE_HOST}\" not found/readable!"
 fi
 
-rsync_cmd=( "${rsync_cmd[@]}" "--rsh=ssh -F $HOME/.ssh/config" "$BACKEND:${REMOTE_DIR}" "${MIRROR_DIR}" )
+rsync_cmd=( "${rsync_cmd[@]}" "--rsh=ssh -F $HOME/.ssh/config-backup" "$BACKEND:${REMOTE_DIR}" "${MIRROR_DIR}" )
 
 # Tar
 if [ ! -x "$TAR_BIN" ]; then
@@ -87,12 +62,11 @@ if [ ! -x "$TAR_BIN" ]; then
 	exit $ERR_TAR
 fi
 
-tar_cmd=( "$TAR_BIN" --create $TAR_PARAMS "--listed-incremental=${SNAPSHOT_FILE}" "--index-file=${LOG_DIR}/listing" "--directory=$(dirname "${MIRROR_DIR}")" )
+tar_cmd=( "$TAR_BIN" --create $TAR_PARAMS "--listed-incremental=${SNAPSHOT_FILE}" "--index-file=${STATUS_DIR}/listing" "--directory=$(dirname "${MIRROR_DIR}")" )
 
-if [ -n "$REFERENCE" ] && [ -r "$REFERENCE" ]; then
-	info "creating incremental backup, using reference \"$REFERENCE\"."
-	ln -s "$(dirname "${REFERENCE}")" "${BACKUP_DIR}"/reference
-	cp -a "$REFERENCE" "${SNAPSHOT_FILE}" || ( error "failed to copy reference file!" ; exit $ERR_TAR )
+if [ -L "${STATUS_DIR}/reference" ]; then
+	info "creating incremental backup, using reference \"$(readlink "${STATUS_DIR}/reference")\"."
+	cp -a "${STATUS_DIR}"/reference/data/"$(basename "${SNAPSHOT_FILE}")" "${SNAPSHOT_FILE}" || ( error "failed to copy reference file!" ; exit $ERR_TAR )
 fi
 
 tar_cmd=( "${tar_cmd[@]}" "$HOST" )
@@ -103,36 +77,34 @@ tar_cmd=( "${tar_cmd[@]}" "$HOST" )
 #
 ################################################################################
 
-size_file="${LOG_DIR}/$(basename "${BACKUP_TAR}").size"
-md5_file="${LOG_DIR}/$(basename "${BACKUP_TAR}").md5sum"
+size_file="${STATUS_DIR}/$(basename "${BACKUP_TAR}").size"
+md5_file="${STATUS_DIR}/$(basename "${BACKUP_TAR}").md5sum"
 
 info "executing '${fakeroot_cmd[@]} ${rsync_cmd[@]}'"
-"${fakeroot_cmd[@]}" "${rsync_cmd[@]}" >"${LOG_DIR}/rsync-stdout.log" 2>"${LOG_DIR}/rsync-stderr.log" || ( errno=$? ; error "rsync failed: $errno" ; exit $ERR_RSYNC )
+"${fakeroot_cmd[@]}" "${rsync_cmd[@]}" >"${STATUS_DIR}/rsync-stdout.log" 2>"${STATUS_DIR}/rsync-stderr.log"
+errno=$?
+
+if (( errno == 24 )); then
+	warn "rsync could not transfer all files as some seem to have vanished (return code 24)"
+
+elif (( errno != 0 )); then
+	error "rsync failed: $errno"
+	exit $ERR_RSYNC
+fi
 
 info "executing '${fakeroot_cmd[@]} ${tar_cmd[@]}'"
-"${fakeroot_cmd[@]}" "${tar_cmd[@]}" 2>"${LOG_DIR}/tar-stderr.log" |
+"${fakeroot_cmd[@]}" "${tar_cmd[@]}" 2>"${STATUS_DIR}/tar-stderr.log" |
 	"${COMPRESS_BIN}" $COMPRESS_PARAMS |
-	tee >(wc --bytes > "$size_file") >(md5sum | dd bs=32 count=1 2>/dev/null >"$md5_file") >"${BACKUP_TAR}"  || ( errno=$? ; error "tar failed: $errno" ; exit $ERR_TAR )
+	tee >(wc --bytes > "$size_file") >(md5sum >"$md5_file") >"${BACKUP_TAR}"
+errno=$?
 
+if (( errno != 0 )); then
+	error "tar failed: $errno"
+	exit $ERR_TAR
+fi
 
 info "verifying backup"
-
-size=$(stat --format='%s' "${BACKUP_TAR}")
-if (( size ==  $(< "$size_file") )); then
-	info "size OK"
-else
-	error "ERR: tar archive size mismatch: is $size, should $(< "$size_file")"
-	exit $ERR_TAR
-fi
-
-info "checking md5sum"
-echo "  ${BACKUP_TAR}" >> "$md5_file"
-if md5sum --check "$md5_file" >/dev/null 2>&1; then
-	info "md5sum OK"
-else
-	error "md5sum of tar archive does not match, backup defect!"
-	exit $ERR_TAR
-fi
+backup-verify "${BACKUP_TAR}" "$size_file" "$md5_file" || exit $ERR_TAR
 
 info "compressing log files"
-"${COMPRESS_BIN}" $COMPRESS_PARAMS "${LOG_DIR}/rsync-stdout.log" "${LOG_DIR}/rsync-stderr.log" "${LOG_DIR}/tar-stderr.log" "${LOG_DIR}/listing"
+"${COMPRESS_BIN}" $COMPRESS_PARAMS "${STATUS_DIR}/rsync-stdout.log" "${STATUS_DIR}/rsync-stderr.log" "${STATUS_DIR}/tar-stderr.log" "${STATUS_DIR}/listing"
diff --git a/bin/backup-mysql b/bin/backup-mysql
--- a/bin/backup-mysql
+++ b/bin/backup-mysql
@@ -30,8 +30,8 @@ remote_mysql_cnf="$($ssh mktemp --suffix=.cnf)"
 remote_backup_dir="$($ssh mktemp --directory --tmpdir=\"${REMOTE_DIR}\")"
 
 # Store recorded size and md5sum of innodb backup here
-innodb_size_file="${LOG_DIR}/$(basename "$BACKUP_INNODB").size"
-innodb_md5sum_file="${LOG_DIR}/$(basename "$BACKUP_INNODB").md5sum"
+innodb_size_file="${STATUS_DIR}/$(basename "$BACKUP_INNODB").size"
+innodb_md5sum_file="${STATUS_DIR}/$(basename "$BACKUP_INNODB").md5sum"
 
 # Write return value of innodb backup process here
 remote_innodb_error_file="$($ssh mktemp)"
@@ -61,7 +61,7 @@ function backup-mysql-cleanup() {
 	$ssh -O exit >/dev/null 2>&1
 	
 	trap - INT TERM EXIT
-	exit
+	exit 0
 }
 
 trap "backup-mysql-cleanup" INT TERM EXIT
@@ -89,9 +89,11 @@ cat >>"$mysql_cnf" <<-ENDL
 	no-timestamp
 ENDL
 
-if [ -n "$REFERENCE" ]; then
-	echo "incremental-lsn = $REFERENCE" >> "$mysql_cnf"
-	info "  using incremental backup from lsn \"$REFERENCE\""
+if [ -L "${STATUS_DIR}/reference" ] && [ -r "${STATUS_DIR}/reference/mysql/xtrabackup_checkpoints" ]; then
+	ref_lsn=$(grep "to_lsn" "${STATUS_DIR}/reference/mysql/xtrabackup_checkpoints" | sed 's/^to_lsn = //')
+	
+	echo "incremental-lsn = $ref_lsn" >> "$mysql_cnf"
+	info "  using incremental backup from lsn \"$ref_lsn\""
 fi
 
 info "Uploading mysql config"
@@ -112,7 +114,7 @@ fi
 
 info "Starting InnoDB backup"
 
-$ssh "( $xtrabackup_bin --defaults-file=\"$remote_mysql_cnf\" \"$remote_backup_dir\" || echo \"\$?\" > \"$remote_innodb_error_file\") | $COMPRESS_BIN $COMPRESS_PARAMS" 2>"${LOG_DIR}/xtrabackup.log" |
+$ssh "( $xtrabackup_bin --defaults-file=\"$remote_mysql_cnf\" \"$remote_backup_dir\" || echo \"\$?\" > \"$remote_innodb_error_file\") | $COMPRESS_BIN $COMPRESS_PARAMS" 2>"${STATUS_DIR}/xtrabackup.log" |
 tee >(md5sum >"$innodb_md5sum_file" 2>/dev/null) >(wc --bytes > "$innodb_size_file") > "$BACKUP_INNODB"
 
 $ssh "test -s \"$remote_innodb_error_file\"" &&
